on:
  push:
    branches: 
      - main

name: Push to S3 bucket

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      IGNORED_FILES: ".gitignore,aws.yml,"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} | tr '\n' ',' | sed 's/\(.*\),/\1 /')" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy files to the S3 bucket
      run: |
        for i in $(echo $CHANGED_FILES | sed "s/,/ /g"); do
          if ! grep -q "$i," <<< $IGNORED_FILES; then
            echo "Uploading $i to S3 bucket"
            aws s3 cp $i s3://blossom-documentation
          fi
        done
