on:
  push:
    branches: 
      - main

name: Push to S3 bucket

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy files to the S3 bucket
      run: |
        for FILE in *; do 
          aws s3api head-object --bucket blossom-documentation --key $FILE 
          if [ $? == 0 ]
          then
          echo "name exists"
          else
          echo "name does not exist"
          fi 
        done
        aws s3 sync . s3://blossom-documentation
