name: Push to S3 bucket

on: pull_request

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      IGNORED_FILES: ".gitignore,.github/workflows/deploy-prod.yml,"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} | tr '\n' ',' | sed 's/\(.*\),/\1 /')" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy changes files to S3
      run: |
        echo "Changed files $CHANGED_FILES"
        for i in $(echo $CHANGED_FILES | sed "s/,/ /g"); do
          echo $i
          if ! grep -q "$i," <<< $IGNORED_FILES; then
            if test -f $i; then
              echo $i
              if [[ $i == *.swift ]]; then
                echo "Uploading $i to S3 docs bucket"
                aws s3 cp $i s3://blossom-documentation-qa
              elif [[ $i == images/* ]]; then
                echo "Uploading $i to S3 asset bucket"
                aws s3 cp $i s3://bananadocs-documentation-assets-qa
              fi
            fi
          fi
        done
